public:
  tables:
    demographics:
      primary_key:
        patientid_pkey:
          columns: [patientid]
      nrows: 0.02
      columns:
        patientid:
          type: char(20)
          default: .na
          not_null: true
          unique: true
        dateofdeath:
          type: Date
          default: .na
          not_null: false
          unique: false
          range:
          - '1980-09-15'
          - '2023-02-01'
          na_ratio: 0.4518536
        lastseen:
          type: Date
          default: .na
          not_null: true
          unique: false
          range:
          - '2010-01-01'
          - '2023-02-01'
          formula: !expr dplyr::if_else(!is.na(dateofdeath), dateofdeath, sample(seq(as.Date('2010-01-01'), as.Date('2023-02-01'), by = "day"), dplyr::n(), TRUE))
          na_ratio: 0.0
        gender:
          type: character
          default: .na
          not_null: true
          unique: false
          na_ratio: 0.05
          values: ['Male', 'Female']
        tmp_patientid_lastseen:
          type: character
          formula: !expr paste0(patientid, "___", lastseen)
    therapies:
      foreign_keys:
        table_line_of_therapy_fkey:
          columns: [tmp_patientid_lastseen]
          references:
            columns: [tmp_patientid_lastseen]
            table: demographics
      nrows: 0.06
      columns:
        tmp_patientid_lastseen:
          type: character
          not_null: true
        patientid:
          type: character
          formula: !expr gsub("___.*$", "", tmp_patientid_lastseen)
        linenumber:
          type: character
          formula: !expr 1:dplyr::n()
          group_by: patientid
        tmp_patientid_linenumber:
          type: character
          formula: !expr paste0(patientid, "___", linenumber)
          not_null: true
        linename:
          type: character
          default: .na
          not_null: true
          unique: true
          na_ratio: 0.16
          formula: !expr simul_line_base(dplyr::n(), c('Drug A', 'Drug B', 'Drug C', 'Drug D'))
          group_by: tmp_patientid_linenumber
        diagnosis:
          type: character
          default: .na
          not_null: false
          unique: false
          na_ratio: 0.16
          formula: !expr sample(paste('Diagnosis', LETTERS[1:6]), 1)
          group_by: patientid
        tmp_lastseen:
          type: Date
          formula: !expr gsub("^.*___", "", tmp_patientid_lastseen)
        tmp_startend_date:
          type: character
          spec: start_end_period
          formula: !expr calc_startend_periods(dplyr::n(), tmp_lastseen, linenumber)
          group_by: patientid
        startdate:
          type: Date
          default: .na
          not_null: false
          unique: false
          na_ratio: 0.16
          formula: !expr gsub(",.*$", "", tmp_startend_date)
        enddate:
          type: Date
          default: .na
          not_null: false
          unique: false
          na_ratio: 0.16
          formula: !expr gsub("^.*,", "", tmp_startend_date)
        tmp_patientid_diagnosis_startend:
          type: character
          formula: !expr paste0(patientid, "___", diagnosis, "___", startdate, ",", enddate)
    visits:
      foreign_keys:
        table_visit_fkey:
          columns: [tmp_patientid_diagnosis_startend]
          references:
            columns: [tmp_patientid_diagnosis_startend]
            table: therapies
      nrows: 0.9
      columns:
        tmp_patientid_diagnosis_startend:
          type: character
          not_null: true
        patientid:
          type: character
          default: .na
          not_null: true
          unique: false
          formula: !expr gsub("___.*$", "", tmp_patientid_diagnosis_startend)
        diagnosis:
          type: character
          default: .na
          not_null: true
          unique: false
          formula: !expr gsub("___", "", stringr::str_extract(tmp_patientid_diagnosis_startend, "___.*___"))
        tmp_startend:
          type: character
          formula: !expr gsub("^.*___", "", tmp_patientid_diagnosis_startend)
        visitdate:
          type: Date
          default: .na
          not_null: true
          unique: false
          group_by: patientid
          formula: !expr gen_visit(dplyr::n(), tmp_startend)
        visittype:
          type: character
          default: .na
          not_null: true
          unique: false
          values:
          - Vitals
          - Treatment
          - Lab
    diagnoses:
      foreign_keys:
        table_diagnoses_fkey:
          columns: [tmp_patientid_diagnosis_startend]
          references:
            columns: [tmp_patientid_diagnosis_startend]
            table: therapies
      nrows: 0.02
      columns:
        tmp_patientid_diagnosis_startend:
          type: character
          not_null: true
        patientid:
          type: character
          default: .na
          not_null: true
          unique: false
          formula: !expr gsub("___.*$", "", tmp_patientid_diagnosis_startend)
        diagnosis:
          type: factor
          default: .na
          not_null: true
          unique: true
          formula: !expr gsub("___", "", stringr::str_extract(tmp_patientid_diagnosis_startend, "___.*___"))
        tmp_startend:
          type: character
          formula: !expr gsub("^.*___", "", tmp_patientid_diagnosis_startend)
        tmp_startdate:
          type: Date
          formula: !expr gsub(",.*$", "", tmp_startend)
        firstlinestartdate:
          type: Date
          default: .na
          not_null: true
          unique: false
          formula: !expr as.Date(min(tmp_startdate))
          group_by: patientid
        diagnosisdate:
          type: Date
          default: .na
          not_null: false
          unique: false
          formula: !expr firstlinestartdate - sample(365:(365*5), 1, TRUE)
          group_by: patientid

